config/routes.rb
Rails.application.routes.draw do
  get 'search', to: "search#index"
  get 'users/profile'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }


  get "/u/:id", to: "users#profile", as: :user

  resources :posts do
    resources :comments
  end
  get "about", to: "pages#about", as: :about

  get "up" => "rails/health#show", as: :rails_health_check

  root "pages#home"
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    def set_query
      if params[:q]
        @q = Post.ransack(params[:q])
        @posts = @q.result

      else
        @q = Post.ransack({})
        @posts = Post.all
      end
    end
  end

 
  
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_form.html.erb
<%= search_form_for(@q, url: search_path, method: :get, class: 'd-flex') do |form| %>
  <%= form.search_field :title_or_body_or_user_email_or_user_name_cont, placeholder: "Search", class: "form-control me-2" %>
    <!-- Here we say title or body or username or useremail should be contained case insensitive -->
    <%= form.submit "Search", class: "btn btn-outline-success" %>
<% end %>

app/views/search/index.html.erb
<h1 class="text-center"><%= pluralize(@posts.count, "Result") %></h1>
<%= render "search/form" %>
<div class="container">
  <table class="table table-dark table-striped">
    <thead>
      <tr>
        <th><%= sort_link(@q, :title, 'Title', default_order: :asc) %></th>
        <th><%= sort_link(@q, :body, 'Blog Content')%></th>
        <th><%= sort_link(@q, :user_name, 'Users')%></th>
      </tr>
    </thead>
    <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.title, post %></td>
        <td><%= post.body.truncate_words(25) %></td>
        <td><%= link_to post.user.name, post.user %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>