config/routes.rb
Rails.application.routes.draw do
  get 'search', to: "search#index"
  get 'users/profile'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }


  get "/u/:id", to: "users#profile", as: :user

  resources :posts do
    resources :comments
  end
  get "about", to: "pages#about", as: :about

  get "up" => "rails/health#show", as: :rails_health_check

  root "pages#home"
end

app/views/layouts/_alerts.html.erb
<% if notice %>
  <p class="alert alert-success" role="alert"><%= notice %></p>
<% elsif alert%>
  <p class="alert alert-danger" role="alert"><%= alert %></p>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "Blog", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "About", about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "Post", posts_path, class: "nav-link" %>
        </li>
        
      </ul>
      <ul style="list-style:none;">
      <% if user_signed_in? %>
      <%= render "layouts/notifications" %>
      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="" role="button" data-bs-toggle="dropdown" aria-expanded="false"  >
            <%= current_user.name  %>
          </a>
          <ul class="dropdown-menu dropdown-menu-lg-end">
            <li><%= link_to "New Post", new_post_path, class: 'dropdown-item' , data: {"turbo": false} %></li>
            <li><%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" , data: {"turbo": false} %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= button_to "Logout", destroy_user_session_path, class: "dropdown-item", method: :delete ,data: {"turbo": false} %></li>          
            
          </ul>
        </li>
        <% else %>
          <div class="d-flex justify-content-center gap-2">
            <li><%= link_to "Sign In", new_user_session_path, class: "text-decoration-none text-blue-500 fw-bold" %></li>
            <li><%= link_to "Sign Up", new_user_registration_path, class: "text-decoration-none text-blue-500 fw-bold" %></li>
          </div>
        <% end %>
        </ul>
    </div>
  </div>
</nav>

app/views/layouts/_notifications.html.erb
<% if current_user %>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <span class="badge rounded-pill bg-danger">
                <%= @unread.count >= 9 ? "9+" : @unread.count %><i class="bi bi-suit-heart-fill"></i>
            </span>
        </a>
        <ul class="dropdown-menu dropdown-menu-lg-end" aria-labelledby="navbarDropdown">
            <% @unread.each do |notification| %>
                <li class="dropdown-item">
                    <%= link_to notification.to_notification.message, notification.to_notification.url %>
                </li>
            <% end %>
            <% if @read.count>0 && @unread.count>0 %>
                <li>
                    <hr class="dropdown-divider" />
                </li>
            <% elsif @read.count + @unread.count == 0%>
                <li class="dropdown-item">No notification yet.</li> 
            <% end %>
            <% @read.each do |notification| %>
                <li class="dropdown-item">
                    <%= link_to notification.to_notification.message, notification.to_notification.url %>
                </li>
            <% end %>
        </ul>
    </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ModernBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
  </head>
  <body>
    <main>
    <header>  
      <%= render "layouts/navbar" %>
      <%= render "layouts/alerts" %>
      </header>
      <%= yield %>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>